name: .NET Azure Functions Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './Codurance.FunctionAPI'    # set this to the path to your web app project, defaults to the repository root

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
      
    - name: Test
      shell: pwsh
      run: dotnet test

    - name: Deploy to Azure Function App
      if: github.ref == 'refs/heads/main'
      id: fa
      uses: Azure/functions-action@v1.4.4
      with:
        app-name: 'team-api-academy'
        publish-profile: ${{ secrets.PublishProfile }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
